Jonnitto:
  Image:
    tagName: figure
    inlineSVG: false

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Image:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.Image: true
